### ISSUE TITLE
Add user to dbmaintenance.py causes an error

### ISSUE THREAD

**Issue by chriskewl** [retrocomputacion/retrobbs#5]
This is done on a Raspberry Pi 4 in CLI:

```
admin@c64pi:~/retrobbs $ sudo python3 dbmaintenance.py
----RetroBBS Database maintenance tool----

Database open...
Checking database integrity...
User entries: 0
Total messages: 0
---------------------
Please select action:
---------------------
3: Add user
0: Quit

Your selection:3
User Name:chriskewl
Password (6 to 16 chars):******
First name (enter skip):chris
Last name (enter skip):h
Birthday DD/MM/YYYY (warning, no sanity check performed):01/01/1978
Country (enter skip):usa
New class 1-10 (enter 1):10
Traceback (most recent call last):
  File "/home/admin/retrobbs/dbmaintenance.py", line 310, in <module>
    data.newUser(uname,pw,fname,lname,bday,country,uclass)
TypeError: newUser() takes 7 positional arguments but 8 were given
```
(I removed my password from the screen above and replaced with stars.)

**Comment by retrocomputacion** [comment]
Fixed in latest commit, please test

**Comment by chriskewl** [comment]
Still getting the same bug on the newest version, even copied it from GitHub and got the same response.

```
admin@c64pi:~/retrobbs $ sudo python3 dbmaintenance.py
----RetroBBS Database maintenance tool----

Database open...
Checking database integrity...
User entries: 0
Total messages: 0
---------------------
Please select action:
---------------------
3: Add user
0: Quit

Your selection:3
User Name:ChrisKewl
Password (6 to 16 chars):abc123
First name (enter skip):Chris
Last name (enter skip):H
Birthday DD/MM/YYYY (warning, no sanity check performed):01/01/1978
Country (enter skip):US
New class 1-10 (enter 1):10
Traceback (most recent call last):
  File "/home/admin/retrobbs/dbmaintenance.py", line 309, in <module>
    data.newUser(uname,pw,fname,lname,bday,country,uclass)
TypeError: newUser() takes 7 positional arguments but 8 were given
```

**Comment by retrocomputacion** [comment]
Seems you only downloaded the new dbmaintenance.py, you also need to download common/dbase.py

**Comment by chriskewl** [comment]
You are correct, I updated both and it now works.

Suggestion: When doing an "Update user" or "Delete user" - if sysop just presses Return for "User Name:" have the program go back to the menu, no need to ask again. This way you can get out of that User Name loop.

Thanks!

**Comment by retrocomputacion** [comment]
Thanks!
Yeah, dbmaintenance is really primitive.
Gotta add what you suggested and other missing options.
